### PR TITLE
Automata for complementation from `z3-noodler`

### PR DESCRIPTION
**Pull request by vhavlena**
First example of automata from `z3-noodler` that are input for complementation. It is just a couple of them. If I generate all automata from complementation from `automatark`, we get tens of thousands of automata I guess. In a similar way, I generate automata for universality checking, reduction, intersection, ...

### CODE REVIEW

**Review by tfiedor — APPROVED** [review]
I recommend:
  1. Flatten the directory a little bit (there are three straight nested directories); EDIT: if you will provide more benchmarks in future, besides complementation, then maybe I would recommend to at least merge two subdirectories (e.g. `automatark-complement`, and then have `automatark-inclusion`, etc.)
  2. Mention this new benchmark in README (benchmark description), I think short description suffices (some citation, where the benchmark comes from, and what it contains).

**Comment by vhavlena** [comment]
1. Most likely we want to generate automata for different `smt` benchmarks (in this case it is the `automatark`). The second thing is that to divide the benchmark according to automata operations that are applied on the automata could give us quite strong motivation for the experimental evaluation of automata operations.
2. Yes

**Comment by tfiedor** [comment]
> 1. Most likely we want to generate automata for different `smt` benchmarks (in this case it is the `automatark`). The second thing is that to divide the benchmark according to automata operations that are applied on the automata could give us quite strong motivation for the experimental evaluation of automata operations.
> 2. Yes

I have no issues with that.

**Review by Adda0 — APPROVED** [review]
LGTM. I agree with both points 1. and 2. said above. Adding a readme either in the root of the repo or in the folder with the benchmarks is definitely needed. Otherwise, we all soon forget how the benchmarks were made and used.

**Comment by vhavlena** [comment]
I updated the `README` file. We should update the other parts of README at some point as it contains obsolete information (at least the directory structure of benchmarks does not match).

**Pull request merged**
