### PR TITLE
Simplify benchmarks

### PR DESCRIPTION
**Pull request by jurajsic**
What changed:
- final/initial formula is not formula anymore, but it is given as an enumeration
- state `true` does not exists anymore (it was always in a transition `qX false true`, this transition was useless, so I just removed them)
- target states are not given as a formula (i.e. we could have `qX true (qX | qY)`, now there will be two transitions `qX true qX` and `qX true qY`)
- `true` is renamed to `\true` according to VeriFIT/mata#174, this will probably be a breaking change, so we should update parser first

### CODE REVIEW

**Review by Adda0 — COMMENTED** [review]
LGTM. Should be according to our agreement on these topics.

**Review by Adda0 — APPROVED** [review]
LGTM. Should be according to our agreement on these topics.

**Review by tfiedor — APPROVED** [review]
I'm not going through the changes, I trust it works, or we will simply revert the changes.

Just side note. There is also issue with states that are not of form `q<int>` (e.g. state called `true`). Does this PR solve this issue as well? If not, could you fix it as well?

I will merge this PR, once the parser of mata is fixed.

**Comment by jurajsic** [comment]
> Just side note. There is also issue with states that are not of form `q<int>` (e.g. state called `true`). Does this PR solve this issue as well? If not, could you fix it as well?

I think there was only state `true` which was not conforming to `q<int>`. That state should not exist anymore.

**Comment by tfiedor** [comment]
Since, the mata should be up-to date with this, I'm merging it.

**Pull request merged**
